name: Deploy to cPanel via FTPS

on:
  push:
    branches: [ main ] # Nếu nhánh chính của bạn là master thì sửa main thành master

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Sync files via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env
            **/images/**        # Bỏ qua mọi thư mục có tên images
            **/wp-config.php
            wp-config.php
            wp-config-sample.php
            wp-config-docker.php
            .bangiao/**
            .claude/**
            .github/**
            docker-compose*.yml
            Dockerfile*
